# AkshayGangula/Practice-Project
name: Output information
on: workflow_dispatch
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output Github Context
              run: |
                  echo "Secrets: ${{toJSON(secrets)}}"
                  echo "Envirorments: ${{toJSON(env)}}"
                  echo "GitHub Context: ${{toJSON(github)}}"
                  echo "Event Name: ${{github.event_name}}"
