# AkshayGangula/Practice-Project
name: Output information
on: workflow_dispatch
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output Github Context
              run: |
                  echo "${{toJSON(secrets)}}"
                  echo "${{toJSON(jobs)}}"
                  echo "${{toJSON(github)}}"
                  echo "${{github.event_name}}"
