name: Scheduled Workflow
on:
  schedule:
    - cron: '* * 2,3 12 *'
  workflow_dispatch:

jobs:
  scheduled-task:
    name: Trigger Code Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
