name: Scheduled Workflow
on:
  schedule:
    - cron: '0 1-5 * * *'
  workflow_dispatch:

jobs:
  scheduled-task:
    name: Trigger Code Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
