name: Workflow Run Example
on: 
    workflow_run:
        workflows: [Deployment Exercise 2]
        types: [completed]
jobs:
    echo-string:
        runs-on: ubuntu_latest
        steps:
            - run: echo "I was trigged because 'Deployment Exercise' 2 was completed"

