name: Workflow Run Example
on: 
  workflow_run:
    workflows: 
      - Deployment Exercise 2
    types: 
      - completed

jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I was triggered because 'Deployment Exercise 2' was completed"
